title:             Funny clips
email:             ranvir.singh1114@gmail.com
description:       Home for the most funny videos
author:            Funny clips
baseurl:           ""
url:               "http://blog.funnyclips.me"

# Social Profiles
twitter_username:  
github_username:   singh1114
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
